In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt

In [3]:
data = {
    "delivery_time":[17.68, 12.50, 13.03, 15.88, 14.75, 19.11, 9, 18.83, 80.24, 22.50,
                    41.33, 22, 14.50, 20.75, 25, 30, 16.35, 20, 10.50, 36.10],
    "number_of_cases":[7, 3, 3, 4, 6, 7, 2, 7, 30, 5, 16, 10, 4, 6, 9, 10, 6, 7, 3, 17],
    "distance":[560, 220, 340, 80, 150, 330, 110, 210, 1460, 605, 688, 215, 255, 462, 448,
               776, 200, 132, 36, 770]
}
print(data.items())
df = pd.DataFrame(data)
df.head()

y = df['delivery_time']
X = df[['number_of_cases','distance']]
X = sm.add_constant(X)
fitted_model = sm.OLS(y,X).fit()

dict_items([('delivery_time', [17.68, 12.5, 13.03, 15.88, 14.75, 19.11, 9, 18.83, 80.24, 22.5, 41.33, 22, 14.5, 20.75, 25, 30, 16.35, 20, 10.5, 36.1]), ('number_of_cases', [7, 3, 3, 4, 6, 7, 2, 7, 30, 5, 16, 10, 4, 6, 9, 10, 6, 7, 3, 17]), ('distance', [560, 220, 340, 80, 150, 330, 110, 210, 1460, 605, 688, 215, 255, 462, 448, 776, 200, 132, 36, 770])])


In [5]:
ols_estimate = fitted_model.params
print("OLS Estimates:\n", ols_estimate)

#Variance of OLS Estimate
#Residual Sum of squares (RSS)
rss = np.sum(fitted_model.resid**2)

#Estimate of sigma^2
sigma_squared = rss/(len(y)-len(X.columns))

# Variance-Covariance Matrix (linalg - linear algebra)
var_cov_matrix = sigma_squared * np.linalg.inv(np.dot(X.T, X)) 
print("Variance-Covariance Matrix:\n", var_cov_matrix) 

# Standard Errors of the Estimates 
std_errors = np.sqrt(np.diag(var_cov_matrix)) 
print("Standard Errors:\n", std_errors)

mean_estimate = np.mean(y) 
print("\nMean Estimate:\n", mean_estimate)

OLS Estimates:
 const              3.470719
number_of_cases    1.818826
distance           0.011928
dtype: float64
Variance-Covariance Matrix:
 [[ 1.17133236e+00 -6.15959558e-02 -5.82992735e-04]
 [-6.15959558e-02  4.49378412e-02 -7.51585829e-04]
 [-5.82992735e-04 -7.51585829e-04  1.65796892e-05]]
Standard Errors:
 [1.08228109 0.21198547 0.00407182]

Mean Estimate:
 23.002500000000005
